# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True, default='Hello! I enjoy the opportunity to upload entries, create reminders, and plan ahead on this website!'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='about',
            field=models.TextField(default='No content yet!'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ingredients',
            field=models.TextField(default='No key info.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='steps',
            field=models.TextField(default='None.'),
        ),
    ]
