# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-05 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20190702_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
