# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20190707_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_posted',
            new_name='date_last_edited',
        ),
    ]
