# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20190707_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(default='cat_pics/default.png', upload_to='food_pics'),
        ),
    ]
