# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_extrainformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainformation',
            name='author',
        ),
    ]
