# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20190804_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_last_edited',
        ),
    ]
