# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_remove_entry_date_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
